trigger:
  - main

pool:
  vmImage: 'ubuntu-22.04'

variables:
  azureSubscription: 'my-connection'
  terraformWorkingDirectory: 'environments/dev/'  

stages:
- stage: TerraformDeployment
  displayName: 'Deploy Azure Resources with Terraform'
  jobs:
  - job: ApplyTerraform
    displayName: 'Apply Terraform Configuration'
    steps:
    - checkout: self  

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)

    - script: |
        cd $(terraformWorkingDirectory)
        terraform init
      displayName: 'Initialize Terraform'

    - script: |
        cd $(terraformWorkingDirectory)
        terraform plan -out=tfplan
      displayName: 'Plan Terraform Changes'

    - script: |
        cd $(terraformWorkingDirectory)
        terraform apply -auto-approve tfplan
      displayName: 'Apply Terraform Changes'
