trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: my-secrets
  azureSubscription: 'sconnection'
  terraformWorkingDirectory: 'environments/dev/'  

stages:
- stage: TerraformDeployment
  displayName: 'Deploy Azure Resources with Terraform'
  jobs:
  - job: ApplyTerraform
    displayName: 'Apply Terraform Configuration'
    steps:
    - checkout: self  

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
          az account set --subscription $(azureSubscription)

    - script: |
        echo "ARM_CLIENT_ID: $(ARM_CLIENT_ID)"
        echo "ARM_TENANT_ID: $(ARM_TENANT_ID)"
      displayName: 'Debug Environment Variables'

    - script: |
        cd $(terraformWorkingDirectory)
        terraform init
      displayName: 'Initialize Terraform'

    - script: |
        cd $(terraformWorkingDirectory)
        terraform plan -out=tfplan
      displayName: 'Plan Terraform Changes'

    - script: |
        cd $(terraformWorkingDirectory)
        terraform apply -auto-approve tfplan
      displayName: 'Apply Terraform Changes'
